apiVersion: apps/v1
kind: Deployment
metadata:
  name: iron-db
spec:
  selector:
    matchLabels:
      db: mariadb
  template:
    metadata:
      labels:
        db: mariadb
    spec:
      containers:
      - name: iron-db
        image: kodekloud/irondb:2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: db
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Braavo
        - name: MYSQL_DATABASE
          value: lychee
        - name: MYSQL_USER
          value: lychee
        - name: MYSQL_PASSWORD
          value: lychee
      volumes:
      - name: db
        emptyDir: {}
