apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: "2021-03-05T12:36:48Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: jekyll-site
  resourceVersion: "1531"
  selfLink: /api/v1/persistentvolumes/jekyll-site
  uid: 73f01110-7daf-11eb-992c-0242ac110010
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /site
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Available